# This is a basic workflow to help you get started with Actions

name: Render README

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - README.Rmd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "render"
  render:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # Runs a single command using the runners shell
    - name: install rmarkdown and gratia
      run: Rscript -e 'install.packages(c("rmarkdown","gratia"))'

    # Runs a set of commands using the runners shell
    - name: render README
      run: Rscript -e 'rmarkdown::render("README.Rmd")'

    - name: commit rendered README
      run: |
        git commit README.md -m "Re-build README.md" || echo "No changes to commit"
        git push origin master || echo "No changes to commit"
